# Generated by Django 3.2.8 on 2021-10-16 01:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nepal1',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('ddgn', models.FloatField(blank=True, null=True)),
                ('first_dcod', models.FloatField(blank=True, null=True)),
                ('first_dist', models.CharField(blank=True, max_length=50, null=True)),
                ('first_gn_c', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('first_stat', models.FloatField(blank=True, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('centroid_x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('centroid_y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'nepal1',
                'managed': False,
            },
        ),
    ]
