# Generated by Django 3.2.8 on 2021-10-17 00:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepalDistricts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('district', models.CharField(blank=True, db_column='DISTRICT', max_length=50, null=True)),
                ('hq', models.CharField(blank=True, db_column='HQ', max_length=50, null=True)),
                ('province', models.IntegerField(blank=True, db_column='PROVINCE', null=True)),
            ],
            options={
                'db_table': 'Nepal_Districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NepalLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('state_code', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('gapa_napa', models.CharField(blank=True, max_length=50, null=True)),
                ('type_gn', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Nepal_Local',
                'managed': False,
            },
        ),
    ]
